### ISSUE TITLE
Incorrect file hash

### ISSUE THREAD

**Issue by trizzosk** [Orange-Cyberdefense/russia-ukraine_IOCs#2]
Filehash: **912342f1c840a42f6b74132f8a7c4ffe7d40fb77**
- is not MD5 nor sha256.

**Comment by cert-orangecyberdefense** [comment]
Hello,
It's a SHA1. Our list can include MD5, SHA1, SHA256, SHA512.
File analysis available here on Tria.ge : https://tria.ge/220225-ztlvvshcc3
